app = "adguard-dns"

[build]
  image = "adguard-flyio:latest"

[[services]]
  internal_port = 53
  protocol = "udp"
  [[services.ports]]
    port = 53

[[services]]
  internal_port = 53
  protocol = "tcp"
  [[services.ports]]
    port = 53

[[services]]
  internal_port = 80
  protocol = "tcp"
  [[services.ports]]
    port = 80
